### PR TITLE
Add Issue and PR templates

### LINKED ISSUE #77: Add Issue Templates and PR Templates
Add issue and PR templates to make it easy for developers and making things easy.

I will make a PR with the fix to this issue.

### PR DESCRIPTION
**Pull request by navendu-pottekkat**
This PR fixes #77 

Add issue and PR templates to make it easy for developers and making things easy.

### CODE REVIEW

**Comment by navendu-pottekkat** [comment]
@riibeirogabriel Check it out and make any changes if necessary

**Comment by riibeirogabriel** [comment]
@navendu-pottekkat seems good, how the users will find this files? github automatically identify this files and show something like a button?

**Comment by navendu-pottekkat** [comment]
@riibeirogabriel yes, when they open a PR or an Issue they see this. In case of issues we have two templates one for feature requests and one for bugs and the user can choose and even create a blank issue if it is not applicable

**Comment by riibeirogabriel** [comment]
@navendu-pottekkat i don't knew about this, awesome!

**Comment by navendu-pottekkat** [comment]
> @navendu-pottekkat i don't knew about this, awesome!

I found it few months back I think but this is the new recommended way by GitHub

**Comment by riibeirogabriel** [comment]
@navendu-pottekkat Do you know a way to spread the project?

**Comment by navendu-pottekkat** [comment]
Yes, wait I will share some ideas in an issue

**Pull request merged**
